In [21]:
import torch 

In [22]:
x = torch.rand(3,requires_grad = True)

In [23]:
x

tensor([0.8754, 0.5830, 0.0083], requires_grad=True)

In [24]:
y = x+2

In [25]:
print(y)

tensor([2.8754, 2.5830, 2.0083], grad_fn=<AddBackward0>)


In [26]:
z = y*y*2

In [27]:
print(z)

tensor([16.5358, 13.3438,  8.0668], grad_fn=<MulBackward0>)


In [28]:
#z = z.mean()

In [47]:
print(z)

tensor(12.6488, grad_fn=<MeanBackward0>)


In [48]:
z.backward()

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

tensor([3.8339, 3.4440, 2.6778])


In [46]:
optimizer = torch.optim.SGD(z,lr = 0.01)

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor

# 不需要梯度的三种形式

In [38]:
x = torch.rand(3,requires_grad = True)

In [39]:
#x.requires_grad(False)

TypeError: 'bool' object is not callable

In [42]:
y = x.detach()

In [43]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([2.4397, 2.8928, 2.7829])
