In [1]:
import torch 

In [6]:
x = torch.empty([2,3]) #torch.empty 创建任意类型的张量

In [7]:
print(x)

tensor([[-7.5019e-25,  4.5794e-41, -7.5019e-25],
        [ 4.5794e-41,  0.0000e+00,  0.0000e+00]])


In [11]:
x = torch.rand(2,2,dtype = torch.double)

In [12]:
print(x)

tensor([[0.7354, 0.6559],
        [0.4141, 0.2399]], dtype=torch.float64)


_在pytorch中表示了原地替换操作

In [13]:
x = torch.rand(4,5)

In [14]:
y = x.view(-1,2,5)

In [15]:
y

tensor([[[0.0462, 0.0946, 0.0135, 0.2394, 0.0776],
         [0.4529, 0.1173, 0.2020, 0.2593, 0.9893]],

        [[0.9884, 0.4655, 0.9721, 0.6239, 0.1646],
         [0.7579, 0.3457, 0.2093, 0.4969, 0.1755]]])

## torch ->numpy  a.numpy()
## numpy ->torch  torch.from_numpy()

In [17]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5).to(device)
    print(x)

tensor([1., 1., 1., 1., 1.], device='cuda:0')


## numpy不能在gpu上运行tensor